[project]
name = "c-script"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llvmlite>=0.45.1",
    "ply>=3.11",
]

[tool.setuptools]
package-dir = {"" = "."}
py-modules = ["main", "lexer", "parser"]
